### ISSUE TITLE
Wrong compression to ktx if occlusion Texture have more 1 channels

### ISSUE THREAD

**Issue by Yason83** [donmccurdy/glTF-Transform#1007] opened 2023-07-02 14:09 UTC
**Describe the bug**
This image was created in RGBA mode and is used in the occlusionTexture.
During the optimization of the GLB file, it compresses it incorrectly. As far as I understand, it expects the image to be one channel.
![2023-07-02_170728](https://github.com/donmccurdy/glTF-Transform/assets/32398829/ff45e954-00a0-4657-88f9-2c8aaa44a189)

Please advise if there is a way to bypass this issue.
Or is it possible to preprocess all occlusionTexture images into grayscale beforehand?

**To Reproduce**
1. Blender add this image  to occlusion_1 in model ![occlusion_1](https://github.com/donmccurdy/glTF-Transform/assets/32398829/f8853931-8952-4633-bce7-8e7d840b161e)
2. Export to glb
3. Compress `gltf-transform uastc input.glb output.glb --level 4 --rdo 4 --zstd 24 --verbose`
4. Extract images `gltf-transform copy output.glb output.gltf`

**Versions:**
 - cli.js 3.4.5 — Command-line interface (CLI) for the glTF Transform SDK.

**Comment by donmccurdy** [comment] 2023-07-03 15:35
Thanks @Yason83! Unless I've misunderstood the KTX-Software CLI's options, I believe the bug may be upstream. I've filed a bug here:

- https://github.com/KhronosGroup/KTX-Software/issues/727

**Comment by Yason83** [comment] 2023-08-18 11:09
Could you give an approximate timeline on when we can expect this issue to be fixed?

**Comment by donmccurdy** [comment] 2023-08-18 21:26
This will depend on when the issue is fixed upstream in KTX-Software and released. I have the impression they are working on it, but I don't know when that will be complete.

**Comment by donmccurdy** [comment] 2024-02-18 13:59
KTX Software v4.3 is now stable — moving this to the glTF Transform v4 milestone.

https://github.com/KhronosGroup/KTX-Software/releases

**Closed** 2024-02-20 01:16 UTC
Labels: bug, package:cli, external
