### ISSUE TITLE
THREE.DRACOLoader: Decoding failed: Failed to decode geometry data.

### ISSUE THREAD

**Issue by canberka** [donmccurdy/glTF-Transform#1015] opened 2023-07-04 11:29 UTC
Hello, we are trying to compress a glb model with draco which the function is

`gltf-transform draco input.glb output.glb`

and we get the error

**THREE.DRACOLoader: Decoding failed: Failed to decode geometry data.** when we are see in viewer

Although we have compressed many models many times, this is the first time we have faced such a situation.

We can fix it manually , We import and export without any changing in blender. Then the function is working and model is decoding succesfully.

![image](https://github.com/donmccurdy/glTF-Transform/assets/36857390/f3d346e9-d143-40c2-a094-18c38ce78caf)

The model of the case Hoshi.glb's download link
https://drive.google.com/file/d/1BXB4QwMbZVtVetv1HMk67QT338EQgS2h/view?usp=sharing

**Comment by donmccurdy** [comment] 2023-07-05 14:01
There appears to be something about the topology of this model's geometry that is breaking compression... I haven't been able to track down the exact cause yet, but it can be worked around by either un-indexing ("unweld") or re-indexing ("weld") the geometry. Probably welding is what you want, because unwelding would increase file size.

Example:

```bash
gltf-transform weld Hoshi.glb Hoshi_reindex.glb
```

**Comment by donmccurdy** [comment] 2023-07-09 21:39
The cause appears to be an upstream issue in the Draco encoder. I've filed a ticket with a simplified version of the model (containing only a single mesh primitive) here:

- https://github.com/google/draco/issues/1013

**Comment by donmccurdy** [comment] 2024-02-20 00:46
Fixed in newer Draco releases. The v4 release of the glTF Transform CLI will contain the fix as well.

**Closed by donmccurdy** 2024-02-20 00:46 UTC
Labels: bug, package:extensions, external
