### ISSUE TITLE
Triangles culled based on viewport situation

### ISSUE THREAD

**Issue by Kredithaichen** [donmccurdy/glTF-Transform#426] opened 2021-11-17 09:00 UTC
**What is happening**
After compressing a .glb-file with gltf-transform meshopt and loading it into my Unity-project, some of the faces are culled unless I look at them from a very steep angle. I am specifically not looking at a flipped normal issue here, as I am not moving to the front or behind the triangles in question when they disappear or reappear respectively. 

For a life example please refer to the attached GIF: 
![randomCulling](https://user-images.githubusercontent.com/31171070/142166331-c70b4154-6e2c-48a9-8421-16a613bf0de9.gif)

**To Reproduce**
1. download the file `CUBE-1.0.8.1.glb` from [Google Drive](https://drive.google.com/drive/folders/1IOV1yHj_pDuNE84bHzunOyyk3l2nrLTm?usp=sharing)
2. Compress them via the command line interface using `gltfpack -i CUBE-1.0.8.1.glb -o CUBE-1.0.8.1.gltfpack.glb
3. Load the resulting file into Unity at runtime via gltfast package, specifically GltfAsset.cs

**Expected behavior**
I expected to see the compressed model with slight loss of positional information. 

**Versions:**
 - UnityVersion: [2020.3.21f1]
 - gltfastVersion: [4.4.5]

**Additional context**
I couldn't verify the problem in the babylonjs.sandbox (file is shown as expected), when trying to confirm via Gestaltor the file couldn't be loaded due to unsupported filename extension. Other .glb files of varying compressions were loaded just fine, so I assume the problem doesn't lie in the Gltfast-package. 
I am using multiple materials on the same mesh and the culling seems to occur along the submesh-borders. I verified the normal orientation before the export, but as of right now I cannot

**Comment by donmccurdy** [comment] 2021-11-17 17:17
I think the issue you've mentioned in https://github.com/atteneder/glTFast/issues/281, about "Normalized Positions will likely produce incorrect results..." is very likely to be the cause, so let's see what the glTFast author thinks about that question. 

Based on the "To Reproduce" steps, it sounds like you're using gltfpack and not gltf-transform? That's fine of course, but you could also try something similar with gltf-transform and see if the results are any different.

```shell
# (1) Merge and clean up the asset.
gltfpack -i input.glb -o tmp.glb -noq

# (2) Pick any one of a/b/c below:

# (a)
gltf-transform quantize tmp.glb output.glb

# (b)
gltf-transform meshopt tmp.glb output.glb --level medium

# (c)
gltf-transform meshopt tmp.glb output.glb --level high
```

In the example above, (b) automatically includes (a), and (c) automatically includes (a) and (b), so this can help to isolate where the problem starts.

**Comment by Kredithaichen** [comment] 2021-11-19 11:54
Thanks for the swift response, in fact we have been trying to use gltf-transform meshopt, but it had its own problems, we opened another issue on that, too: #414 
I'll try to isolate the problem using the steps you proposed, thanks again!

**Comment by Kredithaichen** [comment] 2021-11-19 12:22
Quick update: The base file works as intended. #(1) doesn't seem to produce noticeable changes in itself, no error messages either. 
Command #(a) produces an error ("n.pattern.test is not a function") when used on its own, #(b) and #(c) cause the behavior already observed (culling of faces). Also they continue to throw the Normalized-Positions-Exception, so I suppose I'll have to wait for a response on that front.

**Comment by donmccurdy** [comment] 2021-11-19 18:11
> #(a) produces an error ("n.pattern.test is not a function") when used on its own

Hm I haven't been able to reproduce that with the earlier GLB – this is a recent version of gltf-transform? And using the CLI, or a script? I tried running (a) myself, and got this output – could you check if this still has problems in glTFast? The model is quantized (the first step of meshopt compression) but not otherwise compressed.

https://drive.google.com/file/d/1NXNXJsYN-dEwgtlBboGOo5BM1Hrv9cJo/view?usp=sharing

> Also they continue to throw the Normalized-Positions-Exception

Ok, thanks – the output of a/b/c does pass the [official validator](https://github.com/KhronosGroup/glTF-Validator/) (quick test: `gltf-transform validate input.glb`) for me. The validator can't read vertex data using meshopt compression, so that doesn't tell us the whole story, but I think it's likely the files are valid other than the issue in #414, which affects only (c).

**Comment by donmccurdy** [comment] 2021-11-28 07:23
#414 will be fixed on next release, and it looks like the glTFast author has fixed the remaining issue. I'll close this out, but let me know if there's anything I've missed!

**Closed by donmccurdy** 2021-11-28 07:23 UTC
Labels: question, package:cli
