### ISSUE TITLE
Catch an error on read 'MeshOpt' gltf file

### ISSUE THREAD

**Issue by misty000** [donmccurdy/glTF-Transform#739] opened 2022-12-02 08:57 UTC
**Describe the bug**
catch an error when i read a file that generate by gltfTransform (do meshopt) 

TypeError: Cannot read properties of undefined (reading 'buffer')
    at Function.toView (/Users/chenbin/Projects/learn/gltf-test/node_modules/@gltf-transform/core/dist/core.js:1:2411)

**To Reproduce**

sample codes: https://gitee.com/ellipse/gltf-test/raw/master/meshopt.js

**Versions:**
 - Version: [2.4.6]
 - Environment: [Node.js 16.16.0]

**Additional context**

**Comment by donmccurdy** [comment] 2022-12-02 15:25
Hi! Sorry, I can't reproduce this, and the gitee link above is broken for me:

```
[session-9f465189] Route error: ["Access denied", 4]
```

Perhaps you can share the file and the code here? Are you configuring I/O as shown in the docs below?

https://gltf-transform.donmccurdy.com/classes/extensions.meshoptcompression.html

**Comment by misty000** [comment] 2022-12-03 13:09
```
import fs from 'node:fs/promises'

import {Logger, NodeIO, Verbosity} from '@gltf-transform/core'
import {ALL_EXTENSIONS, MeshoptCompression} from '@gltf-transform/extensions'
import {MeshoptDecoder, MeshoptEncoder} from 'meshoptimizer'
import {meshopt} from '@gltf-transform/functions'

async function mkdir(path) {
    try {
        await fs.mkdir(path)
    } catch (e) {
    }
}

await mkdir('temp')
await mkdir('out')

const uri = 'assets/cube.gltf'
const tempUri = 'temp/cube-methopt.gltf'
const out = 'out/cube.gltf'

await MeshoptDecoder.ready
await MeshoptEncoder.ready

const logger = new Logger(Verbosity.DEBUG)

const io = new NodeIO()
    .registerExtensions(ALL_EXTENSIONS)
    .registerDependencies({
        'meshopt.decoder': MeshoptDecoder,
        'meshopt.encoder': MeshoptEncoder,
    })
    .setLogger(logger)

const doc = await io.read(uri)
await doc.transform(
    meshopt({
        encoder: MeshoptEncoder,
    }),
)
doc.createExtension(MeshoptCompression)
    .setRequired(true)
    .setEncoderOptions({method: MeshoptCompression.EncoderMethod.QUANTIZE})

await io.write(tempUri, doc)

// load meshopt model

/**
 * TypeError: Cannot read properties of undefined (reading 'buffer')
 */
const doc2 = await io.read(tempUri)
```

[cube.zip](https://github.com/donmccurdy/glTF-Transform/files/10146423/cube.zip)

**Comment by misty000** [comment] 2022-12-03 13:10
```
TypeError: Cannot read properties of undefined (reading 'buffer')
    at Function.toView (F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\core\dist\core.js:1:2411)
    at F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\extensions\dist\extensions.js:1:6254
    at Array.forEach (<anonymous>)
    at E._prereadBuffers (F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\extensions\dist\extensions.js:1:6046)
    at E.preread (F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\extensions\dist\extensions.js:1:5903)
    at F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\core\dist\core.js:1:41887
    at Array.forEach (<anonymous>)
    at Function.read (F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\core\dist\core.js:1:41874)
    at exports.NodeIO.readJSON (F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\core\dist\core.js:1:49083)
    at F:\Devel\nodejs\gltf-test\node_modules\@gltf-transform\core\dist\core.js:1:40930
```

**Comment by donmccurdy** [comment] 2022-12-03 23:50
Thanks @misty000 — I am able to reproduce the problem now as well. I believe the `.gltf` file written here is actually OK, but there seems to be a bug when trying to read it back into the library. 

I'll look into this, but if you need a workaround until then: using a `.glb` file instead of `.gltf` should avoid the problem.

**Comment by donmccurdy** [comment] 2022-12-04 21:37
To be fixed by https://github.com/donmccurdy/glTF-Transform/pull/740.

**Closed** 2022-12-04 21:45 UTC
Labels: bug, package:extensions
