### ISSUE TITLE
Cannot find namespace 'GLTF' error

### ISSUE THREAD

**Issue by ukito-pl** [donmccurdy/glTF-Transform#119] opened 2020-10-27 09:58 UTC
Hi, 
I installed @gltf-transform/core package in my typescript nest project with 
` npm i @gltf-transform/core`
Then imported it in my ts file with:
`import { NodeIO, Property, BufferUtils } from '@gltf-transform/core'`
and I'm getting many errors like this:
`node_modules/@gltf-transform/core/dist/io/reader-context.d.ts:14:36 - error TS2503: Cannot find namespace 'GLTF'.`
It seems like typescript can't locate this file https://github.com/donmccurdy/glTF-Transform/blob/master/typings/gltf.d.ts which is located outside of @gltf-transform/core package and is not downloaded during package installation. 
How can I fix this issue?

**Comment by donmccurdy** [comment] 2020-10-27 18:41
Hi, thanks for letting me know about this issue. I'm not quite sure how to fix this yet, since the various subpackages here depend on the same types. I may need to publish the types as their own separate npm package?

In the meantime, you should be able to work around this by including the `gltf.d.ts` file in your own project and referencing it in your `tsconfig.json`:

https://github.com/donmccurdy/glTF-Transform/blob/7982ca5419d77333d3077321f0a0f22d4c66f24f/tsconfig.json#L12-L20

**Comment by donmccurdy** [comment] 2020-10-27 19:07
I'm having a hard time reproducing this in https://repl.it/@DonMcCurdy/glTF-Transform-TS-Test — would you be able to share enough about how your project is set up for me to recreate the issue?

**Comment by ukito-pl** [comment] 2020-10-27 20:04
Thank you for help. It seems that adding typings manually in tsconfig.json fixes the issue.

Regarding reproducing the error: 
After downloading your minimal project to my machine it still fails to compile with the same error. I have typescript 4.0.5 and node v12.16.2. After modyfing tsconfig with typings, namespace errors are gone but there are 2 other errors:

---
typings/draco3d.d.ts:48:33 - error TS7051: Parameter has a name but no type. Did you mean 'arg1: number'?
48      GetFaceFromMesh: (mesh: Mesh, number, array: Array) => number;
                                      ~~~~~~
typings/draco3d.d.ts:58:28 - error TS7051: Parameter has a name but no type. Did you mean 'arg0: Buffer'?
58      GetEncodedGeometryType: (Buffer) => GeometryType;

---

However if I change 'strict' option in tsconfig to 'false' compilation succeeds.

**Comment by donmccurdy** [comment] 2020-10-29 04:13
> However if I change 'strict' option in tsconfig to 'false' compilation succeeds.

Oh! Thank you, this is good to know. That specific issue will be fixed when https://github.com/donmccurdy/glTF-Transform/commit/674474e11010b6584dfb82280e52a11a6cb55edd is released. I should probably enable the 'strict' option in this project; I didn't realize that not using it could affect projects using glTF-Transform as a dependency.  Filed https://github.com/donmccurdy/glTF-Transform/issues/120 for that.

***

I'm working on how to publish the types in https://github.com/KhronosGroup/glTF/issues/1894.

**Comment by donmccurdy** [comment] 2020-10-29 04:59
Could you try with v0.7.5? I'm hoping that will fix both issues.

**Comment by ukito-pl** [comment] 2020-10-29 15:30
Thank you, typing issue is gone for good! :) 
Altough some new errors appeared during compilation in strict mode:
[errors.txt](https://github.com/donmccurdy/glTF-Transform/files/5459468/errors.txt)

**Comment by donmccurdy** [comment] 2020-10-29 18:02
Glad to hear! It will take me a while to resolve the strict mode errors, I think, so I'll track that work in https://github.com/donmccurdy/glTF-Transform/issues/120.

**Closed by donmccurdy** 2020-10-29 18:02 UTC
Labels: bug, package:core
