### ISSUE TITLE
Tighten KTX version dependency

### ISSUE THREAD

**Issue by lexaknyazev** [donmccurdy/glTF-Transform#217] opened 2021-04-07 11:46 UTC
The CLI tool should verify that the installed KTX-Software is not outdated by checking the output of `toktx --version`.

**Comment by donmccurdy** [comment] 2021-04-07 17:18
I'll add a check that compares as much of the version string as I can parse with a [semver-compliant version comparator](https://semver.org/#spec-item-11). Note that the `toktx --version` output does not (quite) follow semver:

```
// toktx:
v4.0.0-rc1~6

// semver:
v4.0.0-rc1.6
```

So, my checks will ensure the version is `>= v4.0.0-rc1`, but not necessarily `>= v4.0.0-rc1~6`. If it is safe to simply replace `~` with `.` I can also do that, but I'd like to understand what convention KTX-Software uses before trying to tweak it here.

/cc @MarkCallow

**Comment by donmccurdy** [comment] 2021-04-07 17:47
Related: https://github.com/KhronosGroup/KTX-Software/issues/389

**Comment by lexaknyazev** [comment] 2021-04-07 18:26
`v4.0.0-rc1~6` refers to the exact commit that affected `tools/toktx` git path with `v4.0.0-rc1` being the version tag and `~6` subtracting six commits back from it. We should just ignore the last part here.

**Comment by donmccurdy** [comment] 2021-04-07 21:02
Awesome, sounds like a semver comparison will work just fine then. Thanks!

**Comment by MarkCallow** [comment] 2021-04-08 06:30
Be aware there won't always be a ~ after the version number. There could be nothing or there could be other characters. The version number is basically the output of `git describe`.

**Comment by donmccurdy** [comment] 2021-05-11 17:10
Recent versions appear to have incremented from `v4.0.0-rc1` to `v4.0.0-5`. According to the semver precedence rules (https://semver.org/#spec-item-11), these newer versions are a _lower_ version compared to `rc1`, `beta`, or `alpha` pre-releases, since the last identifier must be compared in ASCII sort order, causing an issue in https://github.com/donmccurdy/glTF-Transform/pull/246. Would it be possible to increment KTX-Software to `v4.0.1` and use semver or another standard version policy moving forward?

**Comment by MarkCallow** [comment] 2021-05-12 12:10
It is `v4.0.0~5`, a `~` not a `-`. So what follows it is not a pre-release version. In semver parlance it is build metadata, except that it is not preceded by a plus sign and semver does not allow `~`s. Basically semver and `git describe` are fundamentally incompatible. It would be wonderful if they could be made compatible. I want to continue using `git describe` for versioning. Fortunately, for tagged releases the versions will either be, e.g., v4.0.0 or like this one with v4.0.0 followed by ~ and some number. That is because the last commit of each versioned component of the release will either be exactly at the tag or some number of commits earlier. Only developers will see cases with commits after the tag in which case `git describe` will use minus signs `-` to separate parts of the version.

**Comment by donmccurdy** [comment] 2021-05-12 17:37
Hm, I'm not sure what's going on here. The tilde is fine, I can work with that, but this user is seeing a dash and not a tilde:

- User: `v4.0.0-5-gca6f6e7d`
- Me: `v4.0.0~6`

I can't reproduce it, so for now I'm just loosening the KTX-Software version check to a warning instead of an error.

**Comment by MarkCallow** [comment] 2021-05-12 21:50
> v4.0.0-5-gca6f6e7d

The user has built the software themselves. This means they have 5 commits on their branch after the v4.0.0 tag. The last part is the abbreviated object name of the actual commit. This was top of trunk from last Friday until yesterday when I merged another PR. See the `git describe` [documentation](https://git-scm.com/docs/git-describe).

**Comment by MarkCallow** [comment] 2021-05-13 10:27
I considered modifying a version number like `v4.0.0-5-gca6f6e7d` to be  `v4.0.0+5-gca6f6e7d` to be slightly more compliant with semver but `git checkout` understands the `git describe` output so modifying it is not an attractive proposition. I hope you can deal with it the version numbers as they are now.

**Comment by donmccurdy** [comment] 2021-05-14 18:43
I see, thanks – I suppose there's no guarantee that a local build (possibly with edits) will be compatible with glTF-Transform in any case. So I'll stick to the current checks, and just warn rather than throwing an error if the version isn't within the expected range.

**Closed by donmccurdy** 2021-05-14 18:43 UTC
Labels: feature, package:cli, question
