### ISSUE TITLE
Black Surface on objects with Multimaterials

### ISSUE THREAD

**Issue by praptoumache** [donmccurdy/glTF-Transform#144] opened 2020-11-28 19:24 UTC
Hi there,

i really like this this project!

i experienced a weird issue using it - Basically its already written in the title :)
As soon as i convert a glb using etc1s i get black surfaces on multimaterials.

attached a zip with files to see what i am talking abou
[MultimaterialTest.zip](https://github.com/donmccurdy/glTF-Transform/files/5611114/MultimaterialTest.zip)

**Comment by donmccurdy** [comment] 2020-11-28 23:50
Thanks for letting me know! I think the cause of the issue here is that Basis Universal (and some GPU hardware, too) requires compressed textures to have widths and heights that are multiples of 4. In the multi-material example, three of the textures have widths of 681px, and those seem to be broken after compression.

I'm marking this as a bug — the conversion should at least warn about it, or ideally resize the texture, but if you need a quick workaround you can also resize the textures yourself.

**Comment by donmccurdy** [comment] 2020-11-29 04:08
It looks like I've misunderstood something about WebGL's compressed texture requirements. I'm following up in https://github.com/KhronosGroup/KTX-Software/issues/345 to try to resolve that. At the moment, it looks like resizing to the next multiple-of-four is not always enough, and you may need to resize textures to powers of two instead. This appears to be a WebGL-specific constraint.

**Closed** 2020-12-14 06:17 UTC
Labels: bug, package:extensions

**Comment by donmccurdy** [comment] 2020-12-14 06:20
The next release will include:

1. If a texture does not have multiple-of-4 dimensions, it is resized automatically.
1. When a texture does not have power-of-two dimensions, the CLI will warn that it may not work in some devices.
1. Optionally, a `--power-of-two` flag can be used to force resizing to a power of two (instead of a multiple of 4).
